@extends('layouts.app')
@section('content')
@php $en = app()->getLocale()==='en'; @endphp
<section class="section bg-light"><div class="container"><div class="row justify-content-center"><div class="col-lg-10"><div class="card card-sj p-4 p-lg-5"><div class="d-flex align-items-start justify-content-between gap-3 flex-wrap"><div><h1 class="fw-bold mb-2">{{ $en?'Request a Quotation':'ขอใบเสนอราคา' }}</h1><p class="text-muted mb-0">{{ $en?'Send job details, photos and location. Our team will contact you soon.':'กรอกข้อมูล แนบรูปหน้างาน และระบุพิกัด/โลเคชั่น ทีมงานจะติดต่อกลับโดยเร็ว' }}</p></div><span class="badge badge-safety rounded-pill px-3 py-2"><i class="fa-solid fa-shield-halved"></i> {{ $en?'Free initial estimate':'ประเมินเบื้องต้นฟรี' }}</span></div>
<form method="post" action="{{ route('quote.store') }}" enctype="multipart/form-data" class="mt-4" id="quoteForm">@csrf
<div class="row g-4">
 <div class="col-12"><div class="soft-card p-3 p-lg-4"><h5 class="fw-bold mb-3"><span class="step-num d-inline-grid me-2">1</span>{{ $en?'Customer information':'ข้อมูลลูกค้า' }}</h5><div class="row g-3"><div class="col-md-6"><label>{{ $en?'Name':'ชื่อ' }} *</label><input name="name" class="form-control" required value="{{ old('name') }}"></div><div class="col-md-6"><label>{{ $en?'Phone':'เบอร์โทร' }} *</label><input name="phone" class="form-control" inputmode="tel" pattern="[0-9+\- ]{8,20}" required value="{{ old('phone') }}"></div><div class="col-md-6"><label>LINE ID</label><input name="line_id" class="form-control" value="{{ old('line_id') }}"></div><div class="col-md-6"><label>Email</label><input name="email" type="email" class="form-control" value="{{ old('email') }}"></div></div></div></div>
 <div class="col-12"><div class="soft-card p-3 p-lg-4"><h5 class="fw-bold mb-3"><span class="step-num d-inline-grid me-2">2</span>{{ $en?'Job information':'ข้อมูลงาน' }}</h5><div class="row g-3"><div class="col-md-6"><label>{{ $en?'Service Type':'ประเภทบริการ' }}</label><select name="service_id" class="form-select" required><option value="">{{ $en?'Select service':'เลือกบริการ' }}</option>@foreach($services as $s)<option value="{{ $s->id }}" @selected(old('service_id',request('service_id'))==$s->id)>{{ $s->title() }}</option>@endforeach</select></div><div class="col-md-6"><label>{{ $en?'Building Type':'ประเภทอาคาร' }}</label><select name="building_type" class="form-select" required><option value="">{{ $en?'Select building type':'เลือกประเภทอาคาร' }}</option>@foreach(['Condo'=>'คอนโด','Hotel'=>'โรงแรม','Office'=>'สำนักงาน','Factory'=>'โรงงาน','Shopping Mall'=>'ห้างสรรพสินค้า','House'=>'บ้านพักอาศัย','Other'=>'อื่น ๆ'] as $val=>$th)<option value="{{ $val }}" @selected(old('building_type')===$val)>{{ $en?$val:$th }}</option>@endforeach</select></div><div class="col-md-6"><label>{{ $en?'Floors':'จำนวนชั้น' }}</label><div class="counter"><button type="button" class="btn btn-outline-secondary" id="floorMinus">−</button><input name="floors" id="floors" type="number" min="1" max="200" class="form-control" value="{{ old('floors',1) }}"><button type="button" class="btn btn-outline-secondary" id="floorPlus">+</button></div></div><div class="col-md-6"><label>{{ $en?'Budget Range':'งบประมาณโดยประมาณ' }}</label><select name="budget_range" class="form-select"><option value="">{{ $en?'Not sure':'ไม่ทราบ' }}</option><option value="below_50000">{{ $en?'Below 50,000 THB':'ต่ำกว่า 50,000 บาท' }}</option><option value="50000_100000">50,000 - 100,000 THB</option><option value="100000_300000">100,000 - 300,000 THB</option><option value="above_300000">{{ $en?'Above 300,000 THB':'300,000 บาทขึ้นไป' }}</option></select></div><div class="col-md-6"><label>{{ $en?'Place / Building / Project Name':'ชื่อสถานที่ / อาคาร / โครงการ' }}</label><input name="location" class="form-control" placeholder="{{ $en?'ABC Condominium / XYZ Hotel':'คอนโด ABC / โรงแรม XYZ' }}" value="{{ old('location') }}"></div><div class="col-md-6"><label>{{ $en?'Job Details':'รายละเอียดงาน' }}</label><input name="details_short" class="form-control" placeholder="{{ $en?'Short note, e.g. exterior repainting':'เช่น ทาสีภายนอก ซ่อมรอยร้าว' }}"></div></div></div></div>
 <div class="col-12"><div class="soft-card p-3 p-lg-4"><h5 class="fw-bold mb-3"><span class="step-num d-inline-grid me-2">3</span>{{ $en?'Worksite address and map':'ที่อยู่หน้างานและแผนที่' }}</h5><div class="row g-3" data-thai-address><div class="col-md-6"><label>{{ $en?'Province':'จังหวัด' }}</label><select name="province" data-province data-value="{{ old('province') }}" class="form-select" required><option value="">{{ $en?'Select province':'เลือกจังหวัด' }}</option></select></div><div class="col-md-6"><label>{{ $en?'District':'อำเภอ/เขต' }}</label><select name="district" data-district data-value="{{ old('district') }}" class="form-select" required><option value="">{{ $en?'Select district':'เลือกอำเภอ/เขต' }}</option></select></div><div class="col-md-6"><label>{{ $en?'Subdistrict':'ตำบล/แขวง' }}</label><select name="subdistrict" data-subdistrict data-value="{{ old('subdistrict') }}" class="form-select" required><option value="">{{ $en?'Select subdistrict':'เลือกตำบล/แขวง' }}</option></select></div><div class="col-md-6"><label>{{ $en?'Postcode':'รหัสไปรษณีย์' }}</label><input name="postcode" data-postal data-value="{{ old('postcode') }}" class="form-control" readonly required></div><div class="col-12"><label>{{ $en?'Address details':'รายละเอียดที่อยู่' }}</label><textarea name="address" class="form-control" rows="2" required placeholder="{{ $en?'House no., building, floor, room, landmark':'เลขที่ อาคาร ชั้น ห้อง หรือจุดสังเกต' }}">{{ old('address') }}</textarea></div><div class="col-md-8"><label>{{ $en?'Google Maps Link':'ลิงก์ Google Maps' }}</label><input name="map_link" id="map_link" class="form-control" placeholder="https://maps.google.com/?q=18.854859,98.561256" value="{{ old('map_link') }}"></div><div class="col-md-4 d-flex align-items-end"><button type="button" class="btn btn-outline-primary w-100" id="pullMap"><i class="fa-solid fa-map-location-dot"></i> {{ $en?'Pull from Maps':'ดึงจาก Google Maps' }}</button></div><div class="col-md-6"><label>Latitude</label><input name="latitude" id="latitude" class="form-control" placeholder="18.854859" value="{{ old('latitude') }}"></div><div class="col-md-6"><label>Longitude</label><input name="longitude" id="longitude" class="form-control" placeholder="98.561256" value="{{ old('longitude') }}"></div><div class="col-12 d-flex flex-wrap gap-2"><button type="button" class="btn btn-outline-primary" id="useLocation"><i class="fa-solid fa-location-crosshairs"></i> {{ $en?'Use current location':'ใช้ตำแหน่งปัจจุบัน' }}</button><small class="text-muted align-self-center">{{ $en?'Map preview updates automatically when coordinates are available.':'แผนที่จะแสดงตัวอย่างอัตโนมัติเมื่อมีพิกัด' }}</small></div><div class="col-12"><iframe id="mapPreview" class="map-preview" loading="lazy" src="about:blank"></iframe><div id="mapHint" class="small text-muted mt-2">{{ $en?'Paste a Google Maps link or use your current location.':'วางลิงก์ Google Maps หรือกดใช้ตำแหน่งปัจจุบัน' }}</div></div></div></div></div>
 <div class="col-12"><div class="soft-card p-3 p-lg-4"><h5 class="fw-bold mb-3"><span class="step-num d-inline-grid me-2">4</span>{{ $en?'Photos and details':'รูปหน้างานและรายละเอียด' }}</h5><div class="row g-3"><div class="col-12"><label>{{ $en?'Full Job Details':'รายละเอียดงานเพิ่มเติม' }}</label><textarea name="details" class="form-control" rows="5">{{ old('details') }}</textarea></div><div class="col-12"><label>{{ $en?'Job Photos':'รูปหน้างาน' }}</label><input name="images[]" id="jobImages" type="file" multiple accept="image/*" class="form-control"><small class="text-muted">{{ $en?'Max 10 photos, 5MB each. Preview helps prevent duplicate uploads.':'สูงสุด 10 รูป ไม่เกิน 5MB ต่อไฟล์ มีตัวอย่างรูปเพื่อป้องกันอัปโหลดซ้ำ' }}</small><div id="imagePreview" class="preview-grid mt-3"></div></div><div class="col-12"><button class="btn btn-sj btn-lg"><i class="fa-solid fa-paper-plane"></i>{{ $en?'Submit Request':'ส่งข้อมูล' }}</button></div></div></div></div>
</div></form></div></div></div></div></section>
@endsection
@section('scripts')
<script src="{{ asset('js/thai-address.js') }}"></script>
<script>
const en = window.SJ_LOCALE === 'en';
const msg = {
 noGeo: en?'Your browser does not support location services.':'เบราว์เซอร์ไม่รองรับการดึงตำแหน่ง',
 failGeo: en?'Unable to get your location. Please allow location permission or enter the map link manually.':'ไม่สามารถดึงตำแหน่งได้ กรุณาอนุญาตตำแหน่งหรือใส่ลิงก์แผนที่เอง',
 noCoord: en?'No coordinates found in this link. Please paste a link that contains latitude and longitude.':'ไม่พบพิกัดในลิงก์นี้ กรุณาวางลิงก์ที่มี Latitude และ Longitude',
 dup: en?'Duplicate photo skipped.':'ข้ามรูปซ้ำแล้ว',
 max: en?'Maximum 10 photos.':'อัปโหลดได้สูงสุด 10 รูป'
};
const floors = document.getElementById('floors');
document.getElementById('floorMinus')?.addEventListener('click',()=>floors.value=Math.max(1,(parseInt(floors.value||1)-1)));
document.getElementById('floorPlus')?.addEventListener('click',()=>floors.value=Math.min(200,(parseInt(floors.value||1)+1)));
function updateMap(){ const lat=document.getElementById('latitude').value, lng=document.getElementById('longitude').value, frame=document.getElementById('mapPreview'), hint=document.getElementById('mapHint'); if(lat&&lng){ frame.src=`https://www.google.com/maps?q=${encodeURIComponent(lat+','+lng)}&output=embed`; hint.textContent=en?'Map preview is ready.':'แสดงตัวอย่างแผนที่แล้ว'; }}
function extractLatLng(text){ text=text||''; let m=text.match(/@(-?\d+\.\d+),\s*(-?\d+\.\d+)/) || text.match(/[?&]q=(-?\d+\.\d+),\s*(-?\d+\.\d+)/) || text.match(/(-?\d+\.\d+)\s*,\s*(-?\d+\.\d+)/); return m?{lat:m[1],lng:m[2]}:null; }
document.getElementById('pullMap')?.addEventListener('click',()=>{ const found=extractLatLng(document.getElementById('map_link').value); if(!found){ window.sjToast(msg.noCoord); return;} document.getElementById('latitude').value=Number(found.lat).toFixed(7); document.getElementById('longitude').value=Number(found.lng).toFixed(7); updateMap(); });
document.getElementById('map_link')?.addEventListener('input',()=>{ const found=extractLatLng(document.getElementById('map_link').value); if(found){ document.getElementById('latitude').value=Number(found.lat).toFixed(7); document.getElementById('longitude').value=Number(found.lng).toFixed(7); updateMap(); }});
['latitude','longitude'].forEach(id=>document.getElementById(id)?.addEventListener('input',updateMap));
document.getElementById('useLocation')?.addEventListener('click',()=>{if(!navigator.geolocation){window.sjToast(msg.noGeo);return;}navigator.geolocation.getCurrentPosition(pos=>{document.getElementById('latitude').value=pos.coords.latitude.toFixed(7);document.getElementById('longitude').value=pos.coords.longitude.toFixed(7);updateMap();},()=>window.sjToast(msg.failGeo),{enableHighAccuracy:true,timeout:10000});});
const input=document.getElementById('jobImages'), preview=document.getElementById('imagePreview'); const seen=new Set();
input?.addEventListener('change',()=>{ preview.innerHTML=''; seen.clear(); const files=[...input.files]; if(files.length>10){ window.sjToast(msg.max); } files.slice(0,10).forEach(file=>{ const key=file.name+'-'+file.size; if(seen.has(key)){ window.sjToast(msg.dup); return;} seen.add(key); const url=URL.createObjectURL(file); const div=document.createElement('div'); div.className='preview-item'; div.innerHTML=`<img src="${url}" alt=""><div class="cap">${file.name}</div>`; preview.appendChild(div); }); });
updateMap();

document.getElementById('quoteForm')?.addEventListener('submit', (e)=>{
  const form=e.currentTarget;
  const requiredSelectors=['[name="name"]','[name="phone"]','[name="service_id"]','[name="building_type"]','[name="floors"]','[name="province"]','[name="district"]','[name="subdistrict"]','[name="postcode"]','[name="address"]'];
  for(const sel of requiredSelectors){ const el=form.querySelector(sel); if(el && !String(el.value||'').trim()){ e.preventDefault(); el.focus(); window.sjToast(en?'Please complete all required fields.':'กรุณากรอกข้อมูลที่จำเป็นให้ครบ'); return; } }
  const phone=form.querySelector('[name="phone"]');
  if(phone && !/^[0-9+\- ]{8,20}$/.test(phone.value)){ e.preventDefault(); phone.focus(); window.sjToast(en?'Please enter a valid phone number.':'กรุณากรอกเบอร์โทรให้ถูกต้อง'); return; }
  const files=[...(document.getElementById('jobImages')?.files||[])];
  if(files.length>10){ e.preventDefault(); window.sjToast(msg.max); return; }
  for(const f of files){ if(!/^image\/(jpeg|png|webp|gif)$/.test(f.type)){ e.preventDefault(); window.sjToast(en?'Only image files are allowed.':'อัปโหลดได้เฉพาะไฟล์รูปภาพ'); return; } if(f.size>5*1024*1024){ e.preventDefault(); window.sjToast(en?'Each image must be under 5MB.':'รูปแต่ละไฟล์ต้องไม่เกิน 5MB'); return; } }
});

</script>
@endsection
