@extends('layouts.admin')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1">รายงานเจ้าของ</h1><div class="text-muted">Top ขยัน / Top สาย / Top ขาดงาน / Top เบิกเงิน / กำไรต่อใบงาน</div></div><form><input type="month" name="month" value="{{ $month }}" class="form-control" onchange="this.form.submit()"></form></div>
<div class="row g-4">
@foreach([['🏆 Top ขยัน',$topHardWorkers,'work_units','แรง'],['⏰ Top สาย',$topLate,'late_count','ครั้ง'],['🚫 Top ขาดงาน',$topAbsent,'absent_count','ครั้ง'],['💰 Top เบิกเงิน',$topAdvance,'advance_total','บาท']] as $box)
<div class="col-lg-6"><div class="card p-3 h-100"><h5>{{ $box[0] }}</h5>@foreach($box[1] as $i=>$r)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $i+1 }}. {{ $r->employee->name }}</span><b>{{ $box[2]==='advance_total'?number_format($r->{$box[2]}):$r->{$box[2]} }} {{ $box[3] }}</b></div>@endforeach</div></div>
@endforeach
<div class="col-lg-12"><div class="card p-3"><h5>🌟 พนักงานดีเด่น</h5><div class="row">@forelse($hallOfFame as $r)<div class="col-md-3"><div class="border rounded-4 p-3 mb-2"><b>{{ $r->employee->name }}</b><div class="small text-muted">{{ $r->work_units }} แรง / ไม่สาย / ไม่ขาด</div></div></div>@empty<div class="text-muted">ยังไม่มีข้อมูล</div>@endforelse</div></div></div>
<div class="col-lg-12"><div class="card p-3"><h5>📊 สรุปรายคน {{ $start->format('d/m/Y') }} - {{ $end->format('d/m/Y') }}</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>พนักงาน</th><th>แรง</th><th>สาย</th><th>ขาด</th><th>เบิก</th><th>คะแนน</th></tr></thead><tbody>@foreach($rows as $r)<tr><td>{{ $r->employee->name }}</td><td>{{ $r->work_units }}</td><td class="text-warning">{{ $r->late_count }}</td><td class="text-danger">{{ $r->absent_count }}</td><td>{{ number_format($r->advance_total) }}</td><td><span class="badge text-bg-{{ $r->score>=90?'success':($r->score>=75?'warning':'danger') }}">{{ $r->score }}</span></td></tr>@endforeach</tbody></table></div></div></div>
<div class="col-lg-12"><div class="card p-3"><h5>💼 กำไรต่อใบงานล่าสุด</h5><div class="table-responsive"><table class="table"><thead><tr><th>ใบงาน</th><th>ทีม</th><th>รายรับ</th><th>ค่าแรง</th><th>วัสดุ</th><th>อื่น ๆ</th><th>กำไรประมาณ</th></tr></thead><tbody>@foreach($workOrders as $w)<tr><td>{{ $w->work_order_no }}</td><td>{{ $w->workTeam?->name ?: '-' }}</td><td>{{ number_format($w->income_amount) }}</td><td>{{ number_format($w->labor_cost) }}</td><td>{{ number_format($w->material_cost) }}</td><td>{{ number_format($w->other_cost) }}</td><td><b class="{{ $w->profitAmount()>=0?'text-success':'text-danger' }}">{{ number_format($w->profitAmount()) }}</b></td></tr>@endforeach</tbody></table></div></div></div>
</div>
@endsection
