@extends('layouts.admin')
@php
$phones = json_decode($settings['contact_phones'] ?? '[]', true) ?: [];
if(!$phones && !empty($settings['phone'])) $phones=[['label'=>'เบอร์หลัก','label_en'=>'Main phone','number'=>$settings['phone']]];
$socials = json_decode($settings['social_links'] ?? '[]', true) ?: [['name'=>'Facebook','url'=>$settings['facebook_url'] ?? ''],['name'=>'LINE','url'=>$settings['line_url'] ?? ($settings['line_id'] ?? '')]];
@endphp
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="mb-0">ตั้งค่าเว็บไซต์ SJ ทาสีโรยตัว</h1><div class="text-muted">จัดการข้อมูลบริษัท โลโก้ หน้าแรก ติดต่อ SEO และธีม โดยไม่ต้องแก้โค้ด</div></div><a href="{{ route('home') }}" target="_blank" class="btn btn-outline-primary"><i class="fa-solid fa-globe"></i> ดูหน้าเว็บไซต์</a></div>
<form method="post" action="{{ route('admin.settings.update') }}" enctype="multipart/form-data" class="card p-4">@csrf @method('patch')
<ul class="nav nav-pills mb-4 gap-2" role="tablist">
 <li class="nav-item"><button type="button" class="nav-link active" data-bs-toggle="pill" data-bs-target="#company"><i class="fa-solid fa-building"></i> ข้อมูลบริษัท</button></li>
 <li class="nav-item"><button type="button" class="nav-link" data-bs-toggle="pill" data-bs-target="#branding"><i class="fa-solid fa-image"></i> โลโก้ / Favicon</button></li>
 <li class="nav-item"><button type="button" class="nav-link" data-bs-toggle="pill" data-bs-target="#home"><i class="fa-solid fa-house"></i> หน้าแรก</button></li>
 <li class="nav-item"><button type="button" class="nav-link" data-bs-toggle="pill" data-bs-target="#contact"><i class="fa-solid fa-address-book"></i> ติดต่อ / Social</button></li>
 <li class="nav-item"><button type="button" class="nav-link" data-bs-toggle="pill" data-bs-target="#seo"><i class="fa-solid fa-magnifying-glass-chart"></i> SEO / แชร์ลิงก์</button></li>
 <li class="nav-item"><button type="button" class="nav-link" data-bs-toggle="pill" data-bs-target="#theme"><i class="fa-solid fa-palette"></i> Theme</button></li>
 <li class="nav-item"><button type="button" class="nav-link" data-bs-toggle="pill" data-bs-target="#quote"><i class="fa-solid fa-file-signature"></i> ใบเสนอราคา</button></li>
</ul>
<div class="tab-content">
<div class="tab-pane fade show active" id="company"><div class="row g-3"><div class="col-md-6"><label>ชื่อบริษัท TH</label><input name="company_name" class="form-control" value="{{ $settings['company_name'] ?? 'SJ ทาสีโรยตัว' }}"></div><div class="col-md-6"><label>Company Name EN</label><input name="company_name_en" class="form-control" value="{{ $settings['company_name_en'] ?? 'SJ Rope Access Painting' }}"></div><div class="col-md-6"><label>Email</label><input name="email" class="form-control" value="{{ $settings['email'] ?? '' }}"></div><div class="col-md-6"><label>เลขประจำตัวผู้เสียภาษี</label><input name="tax_id" class="form-control" value="{{ $settings['tax_id'] ?? '' }}"></div><div class="col-md-6"><label>ที่อยู่บริษัท TH</label><textarea name="company_address" class="form-control" rows="3">{{ $settings['company_address'] ?? '' }}</textarea></div><div class="col-md-6"><label>Company Address EN</label><textarea name="company_address_en" class="form-control" rows="3">{{ $settings['company_address_en'] ?? '' }}</textarea></div></div></div>
<div class="tab-pane fade" id="branding"><div class="row g-3"><div class="col-md-6"><label>Logo Navbar TH</label><input type="file" name="logo_nav_th" accept="image/*" class="form-control"><div class="small-help">แนะนำ 400x120 PNG/WebP</div>@if(!empty($settings['logo_nav_th_path']))<img class="thumb mt-2" src="{{ asset('storage/'.$settings['logo_nav_th_path']) }}">@endif</div><div class="col-md-6"><label>Logo Navbar EN</label><input type="file" name="logo_nav_en" accept="image/*" class="form-control">@if(!empty($settings['logo_nav_en_path']))<img class="thumb mt-2" src="{{ asset('storage/'.$settings['logo_nav_en_path']) }}">@endif</div><div class="col-md-6"><label>Logo Footer TH</label><input type="file" name="logo_footer_th" accept="image/*" class="form-control">@if(!empty($settings['logo_footer_th_path']))<img class="thumb mt-2" src="{{ asset('storage/'.$settings['logo_footer_th_path']) }}">@endif</div><div class="col-md-6"><label>Logo Footer EN</label><input type="file" name="logo_footer_en" accept="image/*" class="form-control">@if(!empty($settings['logo_footer_en_path']))<img class="thumb mt-2" src="{{ asset('storage/'.$settings['logo_footer_en_path']) }}">@endif</div><div class="col-md-6"><label>Logo Light</label><input type="file" name="logo_light" accept="image/*" class="form-control">@if(!empty($settings['logo_light_path']))<img class="thumb mt-2" src="{{ asset('storage/'.$settings['logo_light_path']) }}">@endif</div><div class="col-md-6"><label>Logo Dark</label><input type="file" name="logo_dark" accept="image/*" class="form-control">@if(!empty($settings['logo_dark_path']))<img class="thumb mt-2" src="{{ asset('storage/'.$settings['logo_dark_path']) }}">@endif</div><div class="col-md-6"><label>Favicon</label><input type="file" name="favicon" accept="image/*,.ico" class="form-control"><div class="small-help">แนะนำ 32x32 หรือ 512x512</div>@if(!empty($settings['favicon_path']))<div class="border rounded p-2 mt-2 d-inline-flex align-items-center gap-2"><img style="width:28px;height:28px" src="{{ asset('storage/'.$settings['favicon_path']) }}"> <span>Browser Tab Preview</span></div>@endif</div></div></div>
<div class="tab-pane fade" id="home"><div class="row g-3"><div class="col-md-6"><label>Hero Title TH</label><textarea name="hero_title_th" class="form-control" rows="2">{{ $settings['hero_title_th'] ?? 'ผู้เชี่ยวชาญงานทาสีอาคารสูงและโรยตัวซ่อมอาคาร' }}</textarea></div><div class="col-md-6"><label>Hero Title EN</label><textarea name="hero_title_en" class="form-control" rows="2">{{ $settings['hero_title_en'] ?? 'High-Rise Painting & Rope Access Repair Specialists' }}</textarea></div><div class="col-md-6"><label>Hero Subtitle TH</label><textarea name="hero_subtitle_th" class="form-control" rows="3">{{ $settings['hero_subtitle_th'] ?? '' }}</textarea></div><div class="col-md-6"><label>Hero Subtitle EN</label><textarea name="hero_subtitle_en" class="form-control" rows="3">{{ $settings['hero_subtitle_en'] ?? '' }}</textarea></div><div class="col-md-6"><label>Hero Banner / รูปเปิดหน้าเว็บ</label><input type="file" name="hero_image" accept="image/*" class="form-control"><div class="small-help">แนะนำ 1920x1080 สำหรับภาพโฆษณาหน้าแรก</div>@if(!empty($settings['hero_image_path']))<img class="thumb mt-2" src="{{ asset('storage/'.$settings['hero_image_path']) }}">@endif</div></div></div>
<div class="tab-pane fade" id="contact"><h5>เบอร์ติดต่อ</h5><div class="small-help mb-2">กรอกชื่อ + เบอร์ เพื่อให้หน้าเว็บแสดงแบบ “081-353-7779 คุณอิ้ด”</div><div id="phoneRows">@foreach($phones as $i=>$p)<div class="row g-2 mb-2 phone-row"><div class="col-md-3"><input name="contact_phones[{{ $i }}][person]" class="form-control" placeholder="ชื่อ TH เช่น คุณอิ้ด" value="{{ $p['person'] ?? $p['label'] ?? '' }}"></div><div class="col-md-3"><input name="contact_phones[{{ $i }}][person_en]" class="form-control" placeholder="Name EN เช่น Mr. Id" value="{{ $p['person_en'] ?? $p['label_en'] ?? '' }}"></div><div class="col-md-4"><input name="contact_phones[{{ $i }}][number]" class="form-control" placeholder="08x-xxx-xxxx" value="{{ $p['number'] ?? '' }}"></div><div class="col-md-2"><button type="button" class="btn btn-outline-danger w-100 remove-row">ลบ</button></div><input type="hidden" name="contact_phones[{{ $i }}][label]" value="{{ $p['person'] ?? $p['label'] ?? '' }}"><input type="hidden" name="contact_phones[{{ $i }}][label_en]" value="{{ $p['person_en'] ?? $p['label_en'] ?? '' }}"></div>@endforeach</div><button type="button" class="btn btn-outline-primary mb-4" id="addPhone"><i class="fa-solid fa-plus"></i> เพิ่มเบอร์</button><h5>ช่องทางติดต่อ Social</h5><div id="socialRows">@foreach($socials as $i=>$s)<div class="row g-2 mb-2 social-row"><div class="col-md-4"><select name="social_links[{{ $i }}][name]" class="form-select">@foreach(['Facebook','LINE','TikTok','YouTube','Google Maps','Messenger','Instagram'] as $ch)<option @selected(($s['name']??'')===$ch)>{{ $ch }}</option>@endforeach</select></div><div class="col-md-6"><input name="social_links[{{ $i }}][url]" class="form-control" placeholder="URL หรือ LINE ID" value="{{ $s['url'] ?? '' }}"></div><div class="col-md-2"><button type="button" class="btn btn-outline-danger w-100 remove-row">ลบ</button></div></div>@endforeach</div><button type="button" class="btn btn-outline-primary mb-4" id="addSocial"><i class="fa-solid fa-plus"></i> เพิ่ม Social</button><div class="row g-3"><div class="col-md-6"><label>Google Maps Link</label><input name="google_maps_link" id="adminMapLink" class="form-control" value="{{ $settings['google_maps_link'] ?? '' }}"></div><div class="col-md-3"><label>Latitude</label><input name="latitude" id="adminLat" class="form-control" value="{{ $settings['latitude'] ?? '' }}"></div><div class="col-md-3"><label>Longitude</label><input name="longitude" id="adminLng" class="form-control" value="{{ $settings['longitude'] ?? '' }}"></div><div class="col-12"><iframe id="adminMapPreview" class="map-preview" src="about:blank"></iframe></div></div></div>
<div class="tab-pane fade" id="seo"><div class="row g-3"><div class="col-md-6"><label>Meta Title TH</label><input name="meta_title_th" class="form-control" value="{{ $settings['meta_title_th'] ?? '' }}"></div><div class="col-md-6"><label>Meta Title EN</label><input name="meta_title_en" class="form-control" value="{{ $settings['meta_title_en'] ?? '' }}"></div><div class="col-md-6"><label>Meta Description TH</label><textarea name="meta_description_th" rows="3" class="form-control">{{ $settings['meta_description_th'] ?? '' }}</textarea></div><div class="col-md-6"><label>Meta Description EN</label><textarea name="meta_description_en" rows="3" class="form-control">{{ $settings['meta_description_en'] ?? '' }}</textarea></div><div class="col-md-6"><label>OG Image / รูปแชร์ Facebook-LINE</label><input type="file" name="og_image" accept="image/*" class="form-control"><div class="small-help">แนะนำ 1200x630</div>@if(!empty($settings['og_image_path']))<img class="thumb mt-2" src="{{ asset('storage/'.$settings['og_image_path']) }}">@endif</div><div class="col-md-6"><label>Browser Theme Color</label><input type="color" name="browser_theme_color" class="form-control form-control-color" value="{{ $settings['browser_theme_color'] ?? '#071b35' }}"></div></div></div>
<div class="tab-pane fade" id="theme"><div class="row g-3"><div class="col-md-4"><label>สี Sidebar Admin (หลัก)</label><input type="color" name="admin_theme_color" class="form-control form-control-color" value="{{ $settings['admin_theme_color'] ?? '#082B5B' }}"></div><div class="col-md-4"><label>สี Accent Admin (รอง)</label><input type="color" name="admin_secondary_color" class="form-control form-control-color" value="{{ $settings['admin_secondary_color'] ?? '#1E6BFF' }}"></div><div class="col-md-4"><label>สีปุ่ม Admin (ทอง)</label><input type="color" name="admin_accent_color" class="form-control form-control-color" value="{{ $settings['admin_accent_color'] ?? '#F4B400' }}"></div><div class="col-md-4"><label>สีหลักหน้าบ้าน User</label><input type="color" name="site_theme_color" class="form-control form-control-color" value="{{ $settings['site_theme_color'] ?? '#082B5B' }}"></div><div class="col-md-4"><label>สี Accent หน้าบ้าน User</label><input type="color" name="site_secondary_color" class="form-control form-control-color" value="{{ $settings['site_secondary_color'] ?? '#1E6BFF' }}"></div><div class="col-md-4"><label>สีปุ่มหน้าบ้าน</label><input type="color" name="site_accent_color" class="form-control form-control-color" value="{{ $settings['site_accent_color'] ?? '#F4B400' }}"></div><div class="col-md-4"><label>โหมด Admin</label><select name="admin_appearance" class="form-select"><option value="light" @selected(($settings['admin_appearance']??'light')==='light')>Light</option><option value="dark" @selected(($settings['admin_appearance']??'light')==='dark')>Dark</option></select></div><div class="col-12"><div class="p-3 rounded-4 border" style="background:linear-gradient(90deg,{{ $settings['site_theme_color'] ?? '#082B5B' }},{{ $settings['site_secondary_color'] ?? '#1E6BFF' }});color:#fff"><b>ตัวอย่าง 2 เฉดสีหน้าเว็บ</b> <span class="badge" style="background:{{ $settings['site_accent_color'] ?? '#F4B400' }};color:#111">ปุ่มสีทอง</span></div></div></div></div>
<div class="tab-pane fade" id="quote"><div class="row g-3"><div class="col-md-6"><label>ข้อมูลบริษัทบนใบเสนอราคา</label><textarea name="quotation_company_info" class="form-control" rows="5">{{ $settings['quotation_company_info'] ?? "SJ ทาสีโรยตัว\nรับทาสีอาคารสูง / โรยตัวซ่อมอาคาร / กันซึม / ล้างกระจก" }}</textarea></div><div class="col-md-6"><label>หมายเหตุ/เงื่อนไขใบเสนอราคา</label><textarea name="quotation_terms" class="form-control" rows="5">{{ $settings['quotation_terms'] ?? "ราคานี้ยังไม่รวม VAT หากมี\nใบเสนอราคามีอายุ 15 วัน\nหน้างานจริงอาจปรับตามการสำรวจ" }}</textarea></div></div></div>
</div><div class="mt-4"><button class="btn btn-sj"><i class="fa-solid fa-floppy-disk"></i> บันทึกทั้งหมด</button></div></form>
@endsection
@section('scripts')<script>
let p={{ count($phones) }}, s={{ count($socials) }};
document.addEventListener('click',e=>{if(e.target.classList.contains('remove-row')) e.target.closest('.row').remove();});
document.getElementById('addPhone').onclick=()=>{document.getElementById('phoneRows').insertAdjacentHTML('beforeend',`<div class="row g-2 mb-2 phone-row"><div class="col-md-3"><input name="contact_phones[${p}][person]" class="form-control" placeholder="ชื่อ TH เช่น คุณอิ้ด"></div><div class="col-md-3"><input name="contact_phones[${p}][person_en]" class="form-control" placeholder="Name EN"></div><div class="col-md-4"><input name="contact_phones[${p}][number]" class="form-control" placeholder="08x-xxx-xxxx"></div><div class="col-md-2"><button type="button" class="btn btn-outline-danger w-100 remove-row">ลบ</button></div></div>`);p++;};
document.getElementById('addSocial').onclick=()=>{document.getElementById('socialRows').insertAdjacentHTML('beforeend',`<div class="row g-2 mb-2 social-row"><div class="col-md-4"><select name="social_links[${s}][name]" class="form-select"><option>Facebook</option><option>LINE</option><option>TikTok</option><option>YouTube</option><option>Google Maps</option><option>Messenger</option><option>Instagram</option></select></div><div class="col-md-6"><input name="social_links[${s}][url]" class="form-control" placeholder="URL หรือ ID"></div><div class="col-md-2"><button type="button" class="btn btn-outline-danger w-100 remove-row">ลบ</button></div></div>`);s++;};
function extractLatLng(text){ text=text||''; let m=text.match(/@(-?\d+\.\d+),\s*(-?\d+\.\d+)/) || text.match(/[?&]q=(-?\d+\.\d+),\s*(-?\d+\.\d+)/) || text.match(/(-?\d+\.\d+)\s*,\s*(-?\d+\.\d+)/); return m?{lat:m[1],lng:m[2]}:null; }
function updateAdminMap(){const lat=document.getElementById('adminLat')?.value,lng=document.getElementById('adminLng')?.value,frame=document.getElementById('adminMapPreview'); if(frame&&lat&&lng) frame.src=`https://www.google.com/maps?q=${lat},${lng}&output=embed`;}
document.getElementById('adminMapLink')?.addEventListener('input',e=>{const f=extractLatLng(e.target.value); if(f){document.getElementById('adminLat').value=Number(f.lat).toFixed(7);document.getElementById('adminLng').value=Number(f.lng).toFixed(7);updateAdminMap();}});['adminLat','adminLng'].forEach(id=>document.getElementById(id)?.addEventListener('input',updateAdminMap)); updateAdminMap();
</script>@endsection
